# Generated by Django 3.2 on 2023-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название URL'),
        ),
    ]
